repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
      
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml
      - id: ruff-format
        args:
          - --config=pyproject.toml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint-fix
        args:
          - --dot
          - --ignore
          - "tests/test_files/**/*"
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.3
    hooks:
      - id: toml-sort-fix
        args: ["--check"]
        exclude: '^(uv\.lock)$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml, --ignore-missing-imports]
        additional_dependencies: [pytest, pydantic, types-cachetools, types-PyYAML]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
        exclude: |
          (?x)^(
              (tests/test_files/.*)|
          )$

      - id: check-docstring-first
        exclude: |
          (?x)^(
              (tests/test_files/.*)|
          )$


      - id: check-merge-conflict
        exclude: |
          (?x)^(
              (tests/test_files/.*)|
          )$

      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              (tests/test_files/.*)|
          )$

      - id: mixed-line-ending
        exclude: |
          (?x)^(
              (tests/test_files/.*)|
          )$

        args:
          - --fix=lf
      - id: trailing-whitespace
        exclude: |
          (?x)^(
              (tests/test_files/.*)|
          )$
